% ========================================================
% PROFILO_UTENTE.PL - Fatti estratti da Steam Web API
% Utente: Domy_nator (SteamID64: 76561198439482035)
% ========================================================

% Generi preferiti (dedotti dallo storico di gioco)
genere_gradito('racing').
genere_gradito('soccer').
genere_gradito('action').
genere_gradito('horror').
genere_gradito('fps').

% Fasce di prezzo considerate accettabili
fascia_prezzo_accettabile('free').
fascia_prezzo_accettabile('budget').
fascia_prezzo_accettabile('mid_price').

% Giochi posseduti / gia' affrontati (per Negation as Failure)
gia_giocato('half_life').
gia_giocato('half_life_2').
gia_giocato('half_life_2_deathmatch').
gia_giocato('half_life_deathmatch_source').
gia_giocato('portal').
gia_giocato('portal_2').
gia_giocato('counter_strike_2').
gia_giocato('the_ship').
gia_giocato('the_ship_single_player').
gia_giocato('the_ship_tutorial').
gia_giocato('eets').
gia_giocato('sherlock_holmes_the_awakened_2008').
gia_giocato('sherlock_holmes_versus_jack_the_ripper').
gia_giocato('bully_scholarship_edition').
gia_giocato('grand_theft_auto_iv_the_complete_edition').
gia_giocato('assassins_creed').
gia_giocato('batman_arkham_asylum').
gia_giocato('silent_hill_homecoming').
gia_giocato('resident_evil_5').
gia_giocato('penumbra_black_plague').
gia_giocato('penumbra_requiem').
gia_giocato('penumbra_overture').
gia_giocato('dark_sector').
gia_giocato('machinarium').
gia_giocato('metro_2033').
gia_giocato('grid_2').
gia_giocato('syberia').
gia_giocato('syberia_2').
gia_giocato('dead_space_2').
gia_giocato('borderlands_2').
gia_giocato('terraria').
gia_giocato('neverwinter').
gia_giocato('max_payne_it').
gia_giocato('alan_wakes_american_nightmare').
gia_giocato('max_payne_3').
gia_giocato('to_the_moon').
gia_giocato('speedrunners').
gia_giocato('max_payne_2_it').
gia_giocato('deponia').
gia_giocato('nights_into_dreams').
gia_giocato('resident_evil_6').
gia_giocato('resident_evil_revelations').
gia_giocato('cry_of_fear').
gia_giocato('pressure').
gia_giocato('warframe').
gia_giocato('outlast').
gia_giocato('sherlock_holmes_crimes_and_punishments').
gia_giocato('the_forest').
gia_giocato('dungeon_of_the_endless').
gia_giocato('rocket_league').
gia_giocato('gameguru_classic').
gia_giocato('cuphead').
gia_giocato('darkwood').
gia_giocato('no_mans_sky').
gia_giocato('metro_2033_redux').
gia_giocato('resident_evil_revelations_2').
gia_giocato('metro_last_light_redux').
gia_giocato('brawlhalla').
gia_giocato('the_witcher_3_wild_hunt_complete_edition').
gia_giocato('kraven_manor').
gia_giocato('resident_evil').
gia_giocato('unturned').
gia_giocato('dirt_rally').
gia_giocato('fahrenheit_indigo_prophecy_remastered').
gia_giocato('resident_evil_0').
gia_giocato('huniepop').
gia_giocato('kholat').
gia_giocato('quiplash').
gia_giocato('black_mesa').
gia_giocato('hollow_knight').
gia_giocato('hue').
gia_giocato('firewatch').
gia_giocato('bulb_boy').
gia_giocato('distraint_deluxe_edition').
gia_giocato('call_of_cthulhu').
gia_giocato('pony_island').
gia_giocato('metro_exodus').
gia_giocato('stardew_valley').
gia_giocato('outlast_2').
gia_giocato('emily_wants_to_play').
gia_giocato('tempest').
gia_giocato('draw_slasher').
gia_giocato('resident_evil_7_biohazard').
gia_giocato('little_nightmares').
gia_giocato('adventurequest_3d').
gia_giocato('kabounce').
gia_giocato('wallpaper_engine').
gia_giocato('z1_battle_royale').
gia_giocato('rusty_lake_hotel').
gia_giocato('a_blind_legend').
gia_giocato('paladins').
gia_giocato('scrap_garden').
gia_giocato('quantum_break').
gia_giocato('hide_and_shriek').
gia_giocato('mini_thief').
gia_giocato('mad_father').
gia_giocato('what_remains_of_edith_finch').
gia_giocato('celeste').
gia_giocato('along_the_edge').
gia_giocato('nierautomata').
gia_giocato('resident_evil_7_teaser_beginning_hour').
gia_giocato('life_is_strange_2').
gia_giocato('bomber_crew').
gia_giocato('police_stories').
gia_giocato('the_search').
gia_giocato('winexy').
gia_giocato('we_were_here').
gia_giocato('visage').
gia_giocato('hunt_showdown_1896').
gia_giocato('graveyard_keeper').
gia_giocato('moonlighter').
gia_giocato('bendy_and_the_ink_machine').
gia_giocato('remothered_tormented_fathers').
gia_giocato('emily_wants_to_play_too').
gia_giocato('stick_fight_the_game').
gia_giocato('we_were_here_too').
gia_giocato('splitgate').
gia_giocato('doki_doki_literature_club').
gia_giocato('simulacra').
gia_giocato('aimlabs').
gia_giocato('blackout_z_slaughterhouse_edition').
gia_giocato('f1_2018').
gia_giocato('breathedge').
gia_giocato('phasmophobia').
gia_giocato('ring_of_elysium').
gia_giocato('hunt_showdown_1896_test_server').
gia_giocato('degrees_of_separation').
gia_giocato('realm_royale_reforged').
gia_giocato('daymare_1998').
gia_giocato('little_nightmares_ii').
gia_giocato('we_were_here_together').
gia_giocato('ultimate_custom_night').
gia_giocato('resident_evil_2').
gia_giocato('destiny_or_fate').
gia_giocato('resident_evil_3').
gia_giocato('resident_evil_resistance').
gia_giocato('heavy_rain').
gia_giocato('beyond_two_souls').
gia_giocato('spongebob_squarepants_battle_for_bikini_bottom_rehydrated').
gia_giocato('hogwarts_legacy').
gia_giocato('spyro_reignited_trilogy').
gia_giocato('warhammer_underworlds_shadespire_edition').
gia_giocato('hollow_knight_silksong').
gia_giocato('ultimate_zombie_defense').
gia_giocato('shipped').
gia_giocato('bendy_and_the_dark_revival').
gia_giocato('song_of_horror').
gia_giocato('twelve_minutes').
gia_giocato('in_sound_mind').
gia_giocato('red_wings').
gia_giocato('horizon_zero_dawn_complete_edition').
gia_giocato('apex_legends').
gia_giocato('tell_me_why').
gia_giocato('resident_evil_village').
gia_giocato('detroit_become_human').
gia_giocato('a_way_out').
gia_giocato('unravel_two').
gia_giocato('resident_evil_reverse').
gia_giocato('keywe').
gia_giocato('this_bed_we_made').
gia_giocato('golden_light').
gia_giocato('life_is_strange_remastered').
gia_giocato('life_is_strange_before_the_storm_remastered').
gia_giocato('crowalt_traces_of_the_lost_colony').
gia_giocato('the_outlast_trials').
gia_giocato('mass_effect_legendary_edition').
gia_giocato('operation_tango').
gia_giocato('we_were_here_forever').
gia_giocato('teenage_mutant_ninja_turtles_shredders_revenge').
gia_giocato('krunker').
gia_giocato('it_takes_two').
gia_giocato('metro_exodus_enhanced_edition').
gia_giocato('knockout_city_cross_play_beta').
gia_giocato('high_on_life').
gia_giocato('uncharted_legacy_of_thieves_collection').
gia_giocato('dead_space').
gia_giocato('tiny_tinas_assault_on_dragon_keep_a_wonderlands_one_shot_adventure').
gia_giocato('luto').
gia_giocato('post_trauma').
gia_giocato('smart_factory_tycoon').
gia_giocato('escape_academy').
gia_giocato('multiversus').
gia_giocato('iron_lung').
gia_giocato('death_stranding_directors_cut').
gia_giocato('in_sink').
gia_giocato('the_last_of_us_part_i').
gia_giocato('clair_obscur_expedition_33').
gia_giocato('amnesia_the_bunker').
gia_giocato('split_fiction').
gia_giocato('portal_with_rtx').
gia_giocato('dokimon').
gia_giocato('resident_evil_4').
gia_giocato('the_finals').
gia_giocato('unsolved_case').
gia_giocato('cronos_the_new_dawn').
gia_giocato('silent_hill_2').
gia_giocato('little_nightmares_enhanced_edition').
gia_giocato('ghost_of_tsushima_directors_cut').
gia_giocato('bunny_guys').
gia_giocato('nubs').
gia_giocato('black_myth_wukong').
gia_giocato('final_sentence').
gia_giocato('horizon_forbidden_west_complete_edition').
gia_giocato('the_last_of_us_part_ii_remastered').
gia_giocato('horizon_zero_dawn_remastered').
gia_giocato('red_dead_redemption').
gia_giocato('wednesdays').
gia_giocato('battlefield_6').
gia_giocato('buckshot_roulette').
gia_giocato('silent_hill_f').
gia_giocato('paragnosia').
gia_giocato('repo').
gia_giocato('the_cabin_factory').
gia_giocato('where_winds_meet').
gia_giocato('resident_evil_requiem').
gia_giocato('resident_evil_3_nemesis_1999').